#!/bin/zsh

t() {
	$TERM "$@" >/dev/null 2>/dev/null &
	disown
}

ldir() {
	test -n "$1" &&
		DIR="$1" ||
		DIR="."
	find $DIR -maxdepth 1 ! -path $DIR -type d
}

nalias() {
	echo -n "Go$1" |
	$EDITOR -s /dev/stdin $ZSH/alias
}

nfunc() {
	{ test -n "$1" &&
		echo -n "Go\n$1() {\n}O" ||
		echo "Go"
	} |
	$EDITOR -s /dev/stdin $ZSH/funcs
}

npath() {
	touch /etc/profile && {
		echo -n "G?^appendpath\noappendpath '$1'OD" |
		$EDITOR -s /dev/stdin /etc/profile
	} || {
		echo -n "Go$1" |
		$EDITOR -s /dev/stdin $ZSH/path
	}
}

clip() { xclip -sel clipboard "$@"}

rcon() {
	ssh kico '\
		docker exec -i $(docker ps | sed -nE "2s/(^[0-9a-f]*).*$/\1/p") rcon-cli '"$@"'\
	'
}

ew() {
	$EDITOR "$(which $1)"
}

ez() {
	$EDITOR "$ZSH/$1"
}

forbranch() {
	for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
		git checkout "$branch"
		eval "$@"
	done
}

owns() {
	pacman -Qo $(which $1)
}

collapse-link() {
		cp --remove-destination -T "$(readlink $1)" $1
}
