#!/bin/zsh

E() {
    newterm $EDITOR $@
}

ldir() {
	test -n "$1" &&
		DIR="$1" ||
		DIR="."
	find $DIR -maxdepth 1 ! -path $DIR -type d
}

nalias() {
	ekeys "gjo$1" $ZSH/alias
}

nfunc() {
	test -n "$1" &&
	ekeys "gjo$1()\\ {\\	}ka" $ZSH/funcs ||
	ekeys "gj" $ZSH/funcs
}

npath() {
	touch /etc/profile && {
		echo -n "gj?^appendpath\noappendpath '$1'OD" |
		$EDITOR /etc/profile
	} || {
		echo -n "gjo$1" |
		ez path
	}
}

clip() { xclip -sel clipboard "$@"}

rcon() {
	ssh kico '\
		docker exec -i $(docker ps | sed -nE "2s/(^[0-9a-f]*).*$/\1/p") rcon-cli '"$@"'\
	'
}

ew() {
	$EDITOR "$(which $1)"
}

ez() {
	$EDITOR "$ZSH/$1"
}

rmw() {
    rm "`which $1`"
}

forbranch() {
	for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
		git checkout "$branch"
		eval "$@"
	done
}

owns() {
	pacman -Qo $(which $1)
}

collapse-link() {
		cp --remove-destination -T "$(readlink $1)" $1
}

mkcd() {
	mkdir -p $1 && cd $1
}
ekeys() {
	keys=$1; shift
	case $EDITOR in
		nvim)
			echo $keys | $EDITOR -s /dev/stdin $@;;
		kak)
			$EDITOR -e "execute-keys $keys" $@
    	esac
}
command_not_found_handler() {
	command-not-found $@
}
ccr() {
	temp=`mktemp` && cc -o $temp $1 && $temp && rm $temp
}
